NextCuisine/Controllers/GuestsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Security.Authentication;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NextCuisine.Data;
using NextCuisine.Models;

namespace NextCuisine.Controllers
{
    public class GuestsController : Controller
    {
        readonly NextCuisineApiClient apiClient = new();
        private readonly NextCuisineContext _context;
        private readonly AwsContext _awsContext = new();

        public GuestsController(NextCuisineContext context)
        {
            _context = context;
        }

        // Authorize a guest's (user's) session
        private void GuestSessionCreate(string uid, string username)
        {
            HttpContext.Session.SetString("uid", uid);
            HttpContext.Session.SetString("username", username);
        }

        private void GuestSessionDelete()
        {
            HttpContext.Session.Remove("uid");
            HttpContext.Session.Remove("username");
        }

        // GET: Guests/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Guest == null)
            {
                return NotFound();
            }
            var guest = await _context.Guest
                .FirstOrDefaultAsync(m => m.Uid == id);
            if (guest == null)
            {
                return NotFound();
            }
            return View(guest);
        }

        // GET: Guests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Guests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Username,Password,RecoveryEmail")] Guest guest)
        {
            // todo check for username conflictions
            if (ModelState.IsValid)
            {
                //    // send the model to the API
                //    _context.Add(guest);
                //    await _context.SaveChangesAsync();
                //    GuestSessionCreate(guest.Uid, guest.Username);
                var resp = await apiClient.SendJsonAsync(HttpMethod.Put, guest, "/guests");
                Debug.WriteLine(resp);
                if (resp.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Details));
                }
            }
            return View(guest);
        }

        // GET: Guests/Login
        public IActionResult Login()
        {
            return View();
        }

        // POST: Guests/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Username,Password")] Guest guest)
        {
            // todo Retrieve the user with the username + password
            Guest? guestMatch = _context.Guest.FirstOrDefault(g => g.Username == guest.Username && g.Password == guest.Password);
            // fail if not match is found
            Debug.WriteLine(guestMatch?.Username);
            if (guestMatch == null)
            {
                return View(guest);
            }
            // authenticate session (via cookies) for 24 hours
            GuestSessionCreate(guestMatch.Uid, guestMatch.Username);
            // redirect to main page
            return Redirect("/uploads");
        }

        [HttpGet("/logout")]
        public IActionResult Logout()
        {
            GuestSessionDelete();
            return Redirect("/");
        }

        // GET: Guests/Edit
        public async Task<IActionResult> Edit()
        {
            try
            {
                var id = HttpContext.Session.GetString("uid") ?? throw new AuthenticationException();
                var guest = await _context.Guest.FindAsync(id);
                if (guest == null)
                {
                    return RedirectToAction(nameof(Create));
                }
                if (guest.Uid != id)
                {
                    return Redirect("/");
                }
                return View(guest);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Login));
            }
        }

        // PATCH: Guests/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Uid, Username,Password,RecoveryEmail")] Guest guest)
        {
            try
            {
                var uid = HttpContext.Session.GetString("uid") ?? throw new AuthenticationException();
                if (ModelState.IsValid && uid == guest.Uid)
                {
                    _context.Update(guest);
                    await _context.SaveChangesAsync();
                }
                ViewBag.Status = "Saved!";
                return View(guest);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Login));
            }
        }

        // GET: Guests/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Guest == null)
            {
                return NotFound();
            }

            if (id == HttpContext.Session.GetString("uid"))
            {
                var guest = await _context.Guest
                    .FirstOrDefaultAsync(m => m.Uid == id);
                if (guest == null)
                {
                    return NotFound();
                }
                return View(guest);
            }
            else
            {
                return Redirect("/");
            }
        }

        // POST: Guests/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed()
        {
            var id = HttpContext.Session.GetString("uid");
            var guest = await _context.Guest.FindAsync(id);
            if (guest != null && id == guest.Uid)
            {
                _context.Guest.Remove(guest);
            }

            await _context.SaveChangesAsync();
            // TODO Delete Profile and S3 Uploads
            return Redirect("/");
        }

        private bool GuestExists(string id)
        {
            return (_context.Guest?.Any(e => e.Uid == id)).GetValueOrDefault();
        }
    }
}

NextCuisine/Controllers/ProfileController.cs
using System.Diagnostics;
using System.Security.Authentication;
using Amazon.DynamoDBv2.DocumentModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NextCuisine.Data;
using NextCuisine.Models;

namespace NextCuisine.Controllers
{
    public class ProfileController : Controller
    {
        private readonly AwsContext _awsContext = new();

        // GET: ProfileController
        public async Task<ActionResult> Index()
        {
            try
            {
                var uid = HttpContext.Session.GetString("uid") ?? throw new AuthenticationException();
                var profile = await _awsContext.GetProfile(uid);
                // create the user's profile if it doesn't exist yet
                if (profile != null) return View(profile);
                profile = new GuestProfile()
                {
                    Uid = uid
                };
                await _awsContext.CreateProfile(profile);
                return View(profile);
            }
            catch
            {
                return Redirect("/guests/login");
            }
        }

        // GET: ProfileController
        [HttpGet("/edit")]
        public async Task<ActionResult> EditPage()
        {
            try
            {
                var profile = await _awsContext.GetProfile(HttpContext.Session.GetString("uid") ?? throw new AuthenticationException());
                return profile == null ? Redirect("/uploads") : View("Edit", profile);
            }
            catch
            {
                return Redirect("/guests/login");
            }
        }

        // GET: ProfileController/Edit
        [HttpPost("/edit")]
        public async Task<IActionResult> EditPost([Bind("Name, Bio, FavoriteRecipes, FavoriteSnacks, GoodCombos")] GuestProfile modifiedProfile)
        {
            try
            {
                string uid = HttpContext.Session.GetString("uid") ?? throw new AuthenticationException();
                await _awsContext.EditProfile(uid, modifiedProfile);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                switch (ex)
                {
                    case AuthenticationException:
                        return Redirect("/guests/login");
                    default:
                        return View("Edit", modifiedProfile);
                }
            }
        }
    }
}

NextCuisine/Views/Guests/Create.cshtml
@model NextCuisine.Models.Guest

@{
    ViewData["Title"] = "Register";
}


<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div class="card text-center bg-light mb-3" style="max-width: 29rem;">
      <div class="card-header">Register Guest</div>
      <div class="card-body">

          <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             
            <div class="form-floating">
                <input asp-for="Username" class="form-control" id="floatingInput" placeholder="User Name"/>
                <label asp-for="Username" class="control-label">User Name</label>
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <p> </p>
            <div class="form-floating">
                <input asp-for="Password" class="form-control" id="floatingPassword" placeholder="Password"/>
                <label asp-for="Password" class="control-label">Password</label>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <p> </p>
            <div class="form-floating">
                <input asp-for="RecoveryEmail" class="form-control" id="floatingInput" placeholder="RecoveryEmail"/>
                <label asp-for="RecoveryEmail" class="control-label">Recovery Email</label>
                <span asp-validation-for="RecoveryEmail" class="text-danger"></span>
            </div>
            <p> </p>
            <div class="form-group">
                 <button type="submit" value="Create" class="btn btn-outline-dark">Register</button>
            </div>
        </form>
          

      </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NextCuisine/Views/Guests/Delete.cshtml
@model NextCuisine.Models.Guest

@{
    ViewData["Title"] = "Delete";
}

<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
<div class="card text-white bg-dark mb-3" style="max-width: 100vh;">
  <div class="card-header">Delete</div>
  <div class="card-body">
      <h3>Are you sure you want to delete this?</h3>
      <h4 class="card-title">Guest</h4>
 <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecoveryEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecoveryEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Uid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="text-light">Back to List</a>
    </form>
  </div>
</div>
</div>

NextCuisine/Views/Guests/Details.cshtml
@model NextCuisine.Models.Guest

@{
    ViewData["Title"] = "Details";
}

<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div class="card text-center bg-light mb-3" style="max-width: 29rem;">
      <div class="card-header">Guest Details</div>
      <div class="card-body"</div>
        <div>
            <hr/>
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Username)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Username)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Password)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Password)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.RecoveryEmail)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.RecoveryEmail)
                </dd>
            </dl>
        </div>

        <div>
            <button class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.Uid">Edit</button> |
            <a class="text-dark" asp-action="Index">Back to List</a>
        </div>
      <p></p>
    </div>
    </div>
</div>

NextCuisine/Views/Guests/Edit.cshtml
@model NextCuisine.Models.Guest

@{
    ViewData["Title"] = "Edit";
}

  <div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
  <div class="card text-center bg-light mb-3" style="max-width: 29rem;">
    <div class="card-header">Edit Guest</div>
    <div class="card-body">
                <form asp-action="Edit" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Uid" />

                    <div class="form-floating">
                        <input asp-for="Username" class="form-control" placeholder="User Name"/>
                        <label asp-for="Username" class="control-label">User Name</label>
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <p> </p>    
                    <div class="form-floating">
                        <input asp-for="Password" class="form-control" placeholder="Password"/>
                        <label asp-for="Password" class="control-label">Password</label>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <p> </p>
                    <div class="form-floating">
                        <input asp-for="RecoveryEmail" class="form-control" placeholder="Recovery Email"/>
                        <label asp-for="RecoveryEmail" class="control-label">RecoveryEmail</label>
                        <span asp-validation-for="RecoveryEmail" class="text-danger"></span>
                    </div>
                    <p> </p>
                    <div class="form-group">
                        <input class="btn btn-success" type="submit" value="Save" />
                    </div>
                </form>
            </div>
        </div>
        <p>
            @ViewBag.Status
        </p>
        <div class="text-center">
            <a class="text-info" asp-controller="Profile" asp-action="Index">Back to Profile</a>
            <a class="text-danger" asp-action="Delete">Delete my Account</a>
        </div>
      
    </div>
    </div>
 </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

NextCuisine/Views/Guests/Login.cshtml
@model Guest

@{
    ViewBag.Title = "Login";
    Layout = "_Layout";
}

<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div class="card text-center bg-light mb-3" style="max-width: 29rem;">
        <div class="card-header">Login To Guest Account</div>
        <div class="card-body">

            <form method="post" asp-controller="Guests" asp-action="Login">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="User Name" asp-for="Username" value="@Model?.Username">
                    <label for="floatingInput">User Name</label>
                </div>
                <p> </p>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Password" autocomplete="off" asp-for="Password" value="@Model?.Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <p> </p>
                <button type="submit" class="btn btn-outline-dark">Login</button>
            </form>

        </div>
    </div>
</div>