NextCuisine/Controllers/UploadsController.cs
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Amazon.S3.Transfer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using NextCuisine.Data;
using NextCuisine.Models;
using NextCuisine.Tools;
using NuGet.Versioning;

namespace NextCuisine.Controllers
{
    public class UploadsController : Controller
    {
        private readonly AwsContext _awsContext = new();

        // GET: UploadsController

        public async Task<ActionResult> Index()
        {
            List<GuestUpload> publicUploads = await _awsContext.GetPublicUploads();
            return View(publicUploads);
        }

        // GET: UploadsController
        [HttpGet]
        public async Task<ViewResult> PrivateUploads()
        {
            List<GuestUpload> publicUploads = await _awsContext.GetPrivateUploads(HttpContext.Session.GetString("uid") ?? throw new InvalidOperationException());
            return View("Index", publicUploads);
        }

        // GET: UploadsController
        [HttpGet]
        public async Task<ActionResult> MyUploads()
        {
            List<GuestUpload> guestUploads = await _awsContext.GetGuestUploads(HttpContext.Session.GetString("uid") ?? throw new InvalidOperationException());
            return View("Index", guestUploads);
        }

        // GET: UploadsController/<Upload_Id>
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            try
            {
                GuestUpload upload = await _awsContext.GetUpload(id) ?? throw new NullReferenceException();
                switch (upload.Visibility)
                {
                    case "Private" when HttpContext.Session.GetString("uid") == upload.OwnerUid:
                        return View(upload);
                    case "Public":
                        return View(upload);
                    default:
                        return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex) { return RedirectToAction(nameof(Index)); }
        }

        [HttpPost]
        public async Task<ActionResult> DetailsFeedback(string id)
        {
            try
            {
                // authenticate via session
                var uid = HttpContext.Session.GetString("uid") ?? throw new BadHttpRequestException("Not logged in");
                var guestProfile = await _awsContext.GetProfile(uid) ?? throw new BadHttpRequestException("Can't find user profile");
                // populate object 
                string feedbackContent = Request.Form["feedback"];
                string feedbackRating = Request.Form["feedback-rating"];
                GuestUploadFeedback feedback = new GuestUploadFeedback
                {
                    OwnerUid = uid,
                    OwnerName = guestProfile.Name ?? "Anonymous User",
                    Content = feedbackContent,
                    Rating = feedbackRating
                };
                // save changes
                Debug.WriteLine($"Owner UID: {uid} | Content + Rating = {feedbackContent + feedbackRating.ToString()}");
                await _awsContext.PostUploadFeedback(id, feedback);
                // refresh upload view
                return Redirect($"/uploads/details/{id}");
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }


        // GET: Uploads/<UploadId>/download => Download Stream
        [HttpGet("/download/{id}/{fileId}")]
        public async Task<IActionResult> Download(string id, string fileId)
        {
            GuestUpload upload = await _awsContext.GetUpload(id) ?? throw new NullReferenceException();
            GuestUploadFile uploadFile = upload.Files.Find(u => u.Id == fileId) ?? throw new InvalidOperationException();
            Debug.WriteLine($"Upload: {uploadFile.Filename} :: Stored in S3 as {uploadFile.FilenameS3}");
            return _awsContext.DownloadGuestFile(uploadFile);
        }

        public async Task<IActionResult> ViewUploadFile(string id, string fileId)
        {
            GuestUpload upload = await _awsContext.GetUpload(id) ?? throw new NullReferenceException();
            GuestUploadFile uploadFile = upload.Files.Find(u => u.Id == fileId) ?? throw new InvalidOperationException();
            //string mimeType = "application/pdf";
            //Response.Headers.Append("Content-Disposition", "inline; filename=" + uploadFile.Filename);
            return await _awsContext.GetGuestFile(uploadFile);
        }

        // GET: UploadsController/Create
        [HttpGet]
        public ActionResult Create()
        {
            var upload = new GuestUpload();
            return View(upload);
        }

        // POST: UploadsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Title, ShortDescription, Content,Visibility")] GuestUpload upload)
        {
            try
            {
                // set owner uid
                upload.OwnerUid = HttpContext.Session.GetString("uid") ?? throw new InvalidOperationException();
                ViewData["LoadText"] = "Uploading now...";
                // upload included files
                if (Request.Form.Files.Count > 0)
                {
                    foreach (IFormFile file in Request.Form.Files)
                    {
                        GuestUploadFile guestUploadFile = new GuestUploadFile()
                        {
                            Filename = file.FileName.Normalize(),
                            FilenameS3 = DataTools.RandomString(15),
                            UploadDateTime = default
                        };
                        // upload to aws blob storage and link to the upload files
                        await _awsContext.UploadGuestFile(guestUploadFile, file.OpenReadStream());
                        upload.Files.Add(guestUploadFile);
                    }
                }
                // upload model object
                await _awsContext.CreateUpload(upload);
                ViewData["LoadText"] = "Created!";
                // send user to feed
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                ViewData["LoadText"] = "An error occurred.";
                return View(upload);
            }
        }

        // GET: UploadsController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            GuestUpload? upload = await _awsContext.GetUpload(id);
            if (upload == null || upload.OwnerUid != HttpContext.Session.GetString("uid"))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(upload);
        }

        // POST: UploadsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, [Bind("Title,ShortDescription,Content,Visibility")] GuestUpload upload)
        {
            try
            {
                // use the original upload to reflect changes
                var originalUpload = await _awsContext.GetUpload(id);
                originalUpload.Title = upload.Title;
                originalUpload.Content = upload.Content;
                originalUpload.ShortDescription = upload.ShortDescription;
                originalUpload.Visibility = upload.Visibility;
                // verify ownership
                if (originalUpload == null || originalUpload.OwnerUid != HttpContext.Session.GetString("uid"))
                {
                    return RedirectToAction(nameof(Index));
                }
                // upload only new files
                if (Request.Form.Files.Count > 0)
                {
                    foreach (IFormFile file in Request.Form.Files)
                    {
                        GuestUploadFile guestUploadFile = new GuestUploadFile()
                        {
                            Filename = file.FileName.Normalize(),
                            FilenameS3 = DataTools.RandomString(15),
                            UploadDateTime = default
                        };
                        // upload to aws blob storage and link to the upload files
                        await _awsContext.UploadGuestFile(guestUploadFile, file.OpenReadStream());
                        originalUpload.Files.Add(guestUploadFile);
                    }
                }
                // commit object and redirect to feed
                await _awsContext.EditUpload(originalUpload);
                return View("Details", upload);
            }
            catch (Exception ex)
            {
                // failed submission; send back with object
                Debug.WriteLine(ex);
                return View(upload);
            }
        }

        // GET: UploadsController/Delete/5
        [HttpGet]
        public async Task<RedirectToActionResult> Delete(string id)
        {
            var uploadObject = await _awsContext.GetUpload(id);
            if (uploadObject != null && uploadObject.OwnerUid == HttpContext.Session.GetString("uid"))
            {
                await _awsContext.DeleteUpload(await _awsContext.GetUpload(id));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: UploadsController/DeleteFile/<FileId>
        [HttpGet("/Uploads/DeleteFile/{fileId}")]
        public async Task<IActionResult> DeleteFile(string fileId)
        {
            try
            {
                // find upload and verify ownership
                var upload = await _awsContext.GetUploadByFileId(fileId);

NextCuisine/Views/Uploads/Create.cshtml
@model GuestUpload

@{
    ViewBag.Title = "Upload";
    Layout = "_Layout";
}

<link type="text/css" rel="stylesheet" href="/css/uploads.css" />

<form method="post" enctype="multipart/form-data" asp-controller="Uploads" asp-action="Create" class="upload-create-form">
    <h2>Create an Upload</h2>
    @Html.AntiForgeryToken()
  
    <div class="form-group">
         <input asp-for="Title" placeholder="Upload Title" maxlength="80"  class="form-control"/>
     </div>

         <p> </p>

    <div class="form-group">
        <input asp-for="ShortDescription" placeholder="Write a short Description" maxlength="500"  class="form-control" />
     </div>
   
         <p> </p>

    <div class="form-group">
         <textarea asp-for="Content" placeholder="Write what's on your mind..." rows="15" style="width: 100%;"  class="form-control">
         </textarea>
     </div>

    <p> </p>

    <div class="form-group">
      <h4>Upload Some Files</h4>
      <input type="file" name="FileInput" multiple />
    </div>

    <p> </p>

    <div class="container">
        <div class="row">
            <div class="form-group col-md-0">
                <select asp-for="Visibility"  class="form-select" style="width: auto;">
                    <option value="Public">Public</option>
                    <option value="Private">Private</option>
                </select>
            </div>
        </div>
    </div>

    <p> </p>

    <div class="form-group">
        <p class="text-dark">@ViewData["LoadText"]</p>
        <p> </p>
        <button class="btn btn-outline-dark" type="submit">Post</button>
     </div>

</form>

NextCuisine/Views/Uploads/Details.cshtml
@using Microsoft.AspNetCore.Mvc.RazorPages
@using Amazon.S3.Model
@model GuestUpload

@{
    ViewBag.Title = Model.Title + " - NextCuisine Guest Upload";
    Layout = "_Layout";
}

<link type="text/css" rel="stylesheet" href="/css/uploads.css" />

<div class="upload-content">
    <h2>@Model.Title</h2>
    <p>@Model.ShortDescription</p>

    <div class="upload-content-text">
        <p>@Model.Content</p>
    </div>

    @if (Model.Files.Count > 0)
    {
        <div class="upload-files-list">
            <h4>Uploaded Files</h4>
            @foreach (GuestUploadFile uploadFile in Model.Files)
            {
                <div class="upload-file">
                    <p>@uploadFile.Filename</p>
                    <a asp-area="" asp-controller="Uploads" asp-action="Download" asp-route-id="@Model.Id" asp-route-fileId="@uploadFile.Id">
                        <button>Download</button>
                    </a>
                    <a target="_blank" asp-area="" asp-controller="Uploads" asp-action="ViewUploadFile" asp-route-id="@Model.Id" asp-route-fileId="@uploadFile.Id">
                        <button>View</button>
                    </a>
                </div>
            }
        </div>
    }
</div>
<div>
    <div class="upload-feedback">
        @foreach (GuestUploadFeedback feedbackItem in Model.Feedback)
        {
            <div class="feedback-item">
                <p>
                    @{
                        var rating = "";
                        var ratingNumber = int.Parse(feedbackItem.Rating);
                        for (int i = 0; i < ratingNumber; i++)
                        {
                            rating += "\u2b50";
                        }
                    }
                    @rating
                </p>
                <p>@feedbackItem.OwnerName</p>
                <p>@feedbackItem.CreationTime.ToShortDateString()</p>
                <p>@feedbackItem.Content</p>
            </div>
        }
    </div>
    @* Guests can only post one review *@
    @if (Context.Session.GetString("uid") == null)
    {
        <p>You must be signed to access feedback reviews.</p>
    }
    else
    {
        @if (Model.Feedback.Count(f => f.OwnerUid == Context.Session.GetString("uid")) < 1)
        {
            <form class="feedback-container" method="post" asp-controller="Uploads" asp-action="DetailsFeedback" asp-route-id="@Model.Id">
                @Html.AntiForgeryToken()
                <h5>Post a Review</h5>
                <input type="number" name="feedback-rating" min="1" max="5" hidden id="feedback-rating" required/>
                <div class="stars">
                    <input class="star star-5" id="star-5" type="radio" name="star" value="5" onchange="handleRatingChange(this)"/>
                    <label class="star star-5" for="star-5"></label>
                    <input class="star star-4" id="star-4" type="radio" name="star" value="4" onchange="handleRatingChange(this)"/>
                    <label class="star star-4" for="star-4"></label>
                    <input class="star star-3" id="star-3" type="radio" name="star" value="3" onchange="handleRatingChange(this)"/>
                    <label class="star star-3" for="star-3"></label>
                    <input class="star star-2" id="star-2" type="radio" name="star" value="2" onchange="handleRatingChange(this)"/>
                    <label class="star star-2" for="star-2" onclick="handleRatingChange"></label>
                    <input class="star star-1" id="star-1" type="radio" name="star" value="1" onchange="handleRatingChange(this)"/>
                    <label class="star star-1" for="star-1"></label>
                </div>
                <script>
                    function handleRatingChange(input) {
                        const ratingValue = input.value;
                        document.getElementById("feedback-rating").value = ratingValue;
                    }
                </script>
                @* Feedback text content *@
                <textarea name="feedback" required></textarea>
                @* Submit *@
                <button type="submit">Post Review</button>
            </form>
        }
        else
        {
            <p>You have already posted a review.</p>
        }
    }
</div>

NextCuisine/Views/Uploads/Edit.cshtml
@model GuestUpload

@functions {
    private IEnumerable<SelectListItem> GetVisibilityList()
    {
        return new List<SelectListItem>
        {
            new SelectListItem { Value = "Public", Text = "Public" },
            new SelectListItem { Value = "Private", Text = "Private" },
        };
    }

}

@{
    ViewBag.Title = "Edit Upload";
    Layout = "_Layout";
}
      
<link type="text/css" rel="stylesheet" href="/css/uploads.css" />
      
<p> </p>
      
<h2>Editing @Model.Title</h2>
      
<form method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <input asp-for="Title" placeholder="Upload Title" maxlength="80" class="form-control" />
    </div>

     <p> </p>

    <div class="form-group">
        <input asp-for="ShortDescription" placeholder="Write a short Description" maxlength="500" class="form-control" />
    </div>

     <p> </p>

    <div class="form-group">
        <textarea asp-for="Content" placeholder="Write what's on your mind..." rows="15" style="width: 100%;" class="form-control">
            @Model.Content
        </textarea>
    </div>
  
    <script type="text/javascript">
        function deleteFile(id) {
            document.getElementById(id).textContent = "Deleted";
        }
    </script>
    @foreach (var file in Model.Files)
    {
        <p>@file.Filename</p>
        <a target="_blank" href="/Uploads/DeleteFile/@file.Id">
            <button id="file-delete-btn-@file.Id" onclick="deleteFile('file-delete-btn-@file.Id')" type="button">
                Delete File
            </button>
        </a>
    }
  
    <p> </p>
    <div class="form-group">
        <h4>Upload Some Files</h4>
        <input type="file" name="FileInput" multiple />
    </div>
    <p> </p>

    @Html.DropDownListFor(model => model.Visibility, GetVisibilityList(), "", new { @class = "form-control", @name = "Visibility"})
      <p> </p>
    <p class="text-dark">@ViewData["LoadText"]</p>

     <p> </p>
    <div class="form-group">
        <button type="submit">Edit</button>
    </div>
</form>

 <p> </p>

<div class=" d-flex justify-content-end align-items-end">
<a href="/uploads/delete/@Model.Id" class="badge bg-danger">
    Delete
</a>
</div>

NextCuisine/Views/Uploads/Index.cshtml
@model List<GuestUpload>

@{
    ViewBag.Title = "Guest Uploads";
    Layout = "_Layout";
}
<link type="text/css" rel="stylesheet" href="/css/uploads.css" />

<h2>Guest Uploads</h2>

<div class="uploads">
    @foreach (var upload in Model)
    {
        var uploadFileCount = upload.Files.Count;
        var uploadRatingCount = upload.Feedback.Count;
        var uploadRatingAverage = 0.0;
        if (uploadRatingCount > 0)
        {
            uploadRatingAverage = upload.Feedback.Average(f => int.Parse(f.Rating));
        }

        <div class="upload-item">
            <h2>@upload.Title</h2>
            <p>@upload.ShortDescription</p>
            <a asp-controller="Uploads" asp-action="Details" asp-route-id="@upload.Id">Read More</a>
            <div>
                @if (uploadRatingCount < 1)
                {
                    <p>There are no ratings yet.</p>
                }
                else
                {
                    <p>@($"{uploadRatingCount} rating(s) with an average of {uploadRatingAverage:0.0}/5.0")</p>
                }
            </div>
            @* Owner Options *@
            @if (upload.OwnerUid == Context.Session.GetString("uid"))
            {
                <a asp-controller="Uploads" asp-action="Edit" asp-route-id="@upload.Id">Edit my Upload</a>
                <a asp-controller="Uploads" asp-action="Delete" asp-route-id="@upload.Id">Delete</a>
            }
        </div>
    }
</div>